/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-tint": "#adc6ff",
                "on-secondary-container": "#b1b4c3",
                "outline-variant": "#424754",
                "on-tertiary": "#003915",
                "surface-dim": "#10131a",
                "inverse-surface": "#e1e2eb",
                "on-secondary-fixed-variant": "#434653",
                "on-secondary-fixed": "#171b26",
                "surface-container-high": "#272a31",
                "error-container": "#93000a",
                "tertiary-fixed": "#6bff8f",
                "on-secondary": "#2c303c",
                "inverse-on-surface": "#2e3037",
                "on-surface-variant": "#c2c6d6",
                "on-primary-fixed-variant": "#004395",
                "tertiary-container": "#00a74b",
                "surface-container-lowest": "#0b0e14",
                "surface": "#10131a",
                "on-primary": "#002e6a",
                "primary-fixed": "#d8e2ff",
                "on-background": "#e1e2eb",
                "surface-container": "#1d2026",
                "inverse-primary": "#005ac2",
                "surface-container-low": "#191c22",
                "primary-fixed-dim": "#adc6ff",
                "on-tertiary-fixed-variant": "#005321",
                "primary": "#adc6ff",
                "secondary-fixed": "#dfe2f1",
                "tertiary": "#4ae176",
                "on-error": "#690005",
                "on-primary-fixed": "#001a42",
                "surface-variant": "#32353c",
                "on-error-container": "#ffdad6",
                "primary-container": "#4d8eff",
                "surface-container-highest": "#32353c",
                "outline": "#8c909f",
                "tertiary-fixed-dim": "#4ae176",
                "secondary": "#c3c6d5",
                "on-tertiary-container": "#003111",
                "secondary-container": "#434653",
                "surface-bright": "#363940",
                "on-tertiary-fixed": "#002109",
                "on-primary-container": "#00285d",
                "error": "#ffb4ab",
                "on-surface": "#e1e2eb",
                "background": "#10131a",
                "secondary-fixed-dim": "#c3c6d5"
            },
            fontFamily: {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
        },
    },
    plugins: [],
}
